---
- name: Adding SaltStack apt repo key
  ansible.builtin.apt_key:
    url: https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/salt-archive-keyring.gpg
    state: present

- name: Adding SaltStack apt repo
  ansible.builtin.apt_repository:
    repo: deb https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal main
    filename: saltstack
    state: present

- name: Installing salt-minion, git and gnupg
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - salt-minion
    - git
    - gnupg

- name: Stopping and disabling salt-minion service
  ansible.builtin.systemd:
    name: salt-minion
    state: stopped
    enabled: false

- name: Fetching Remnux state files
  ansible.builtin.git:
    repo: https://github.com/REMnux/salt-states.git
    dest: /srv/salt

- name: Setting Remnux username to 'vagrant'
  ansible.builtin.lineinfile:
    path: /srv/salt/remnux/config/user.sls
    search_string: 'set user'
    line: "{% set user = salt['pillar.get']('remnux_user', 'vagrant') %}"

- name: Runing Remnux installer
  ansible.builtin.command: salt-call -l debug --local state.sls remnux.cloud

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:

- name: Updating Remnux VM
  ansible.builtin.command: remnux update

- name: Upgrading Remnux VM
  ansible.builtin.command: remnux upgrade

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:
