---
- name: Adding SaltStack apt repo key
  ansible.builtin.apt_key:
    url: "{{ saltstack_repo }}/salt-archive-keyring.gpg"
    state: present

- name: Adding SaltStack apt repo
  ansible.builtin.apt_repository:
    repo: deb {{ saltstack_repo }} focal main
    filename: salt
    state: present

- name: Installing dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - "{{ remnux_deps }}"

- name: Stopping and disabling salt-minion service
  ansible.builtin.systemd:
    name: salt-minion
    state: stopped
    enabled: false

- name: Fetching Remnux installer
  ansible.builtin.get_url:
    url: "{{ remnux_installer }}"
    dest: /usr/local/bin/remnux
    checksum: sha256:{{ remnux_checksum }}
    mode: '0755'

- name: Runing Remnux installer
  ansible.builtin.shell:
    cmd: remnux install --mode=cloud --user={{ remnux_user }}

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:

- name: Ensuring password is set
  ansible.builtin.shell:
    cmd: echo '{{ remnux_user }}:{{ remnux_passwd }}' | chpasswd

- name: Updating Remnux VM
  ansible.builtin.shell:
    cmd: remnux update

- name: Updating Remnux VM
  ansible.builtin.shell:
    cmd: remnux upgrade

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:

- name: Fixing eth1 static IP
  community.general.interfaces_file:
    iface: eth1
    option: address
    value: 192.168.56.102
    state: present

- name: Fixing eth1 static IP
  community.general.interfaces_file:
    iface: eth1
    option: netmask
    value: 255.255.255.0
    state: present

- name: Restarting networking
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: networking

- name: Configuring inetsim
  ansible.builtin.blockinfile:
    path: /etc/inetsim/inetsim.conf
    insertafter: EOF
    block: |
      service_bind_address    0.0.0.0
      dns_default_ip          192.168.56.102
      https_bind_port         4443

- name: Disabling systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true

- name: Restarting inetsim service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: inetsim
