---
- name: Adding SaltStack apt repo key
  ansible.builtin.apt_key:
    url: https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/salt-archive-keyring.gpg
    state: present

- name: Adding SaltStack apt repo
  ansible.builtin.apt_repository:
    repo: deb https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal main
    filename: saltstack
    state: present

- name: Installing dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - salt-minion
    - git
    - gnupg

- name: Stopping and disabling salt-minion service
  ansible.builtin.systemd:
    name: salt-minion
    state: stopped
    enabled: false

- name: Fetching Remnux installer
  ansible.builtin.get_url:
    url: https://remnux.org/remnux-cli
    dest: /usr/local/bin/remnux
    checksum: sha256:23c7f4eefa7599ea2c4156f083906ea5fd99df18f306e4bb43eec0430073985a
    mode: '0755'

- name: Runing Remnux installer
  ansible.builtin.shell: remnux install --mode=cloud --user=vagrant

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:

- name: Ensuring password is set to 'vagrant'
  ansible.builtin.shell: echo 'vagrant:vagrant' | chpasswd

- name: Updating and upgrading Remnux VM
  ansible.builtin.shell: remnux update && remnux upgrade

- name: Disabling systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:
