---
- name: Fetching Remnux installer
  ansible.builtin.get_url:
    url: https://github.com/REMnux/remnux-cli/releases/download/v1.3.4/remnux-cli-linux
    dest: /usr/local/bin/remnux
    checksum: sha256:https://github.com/REMnux/remnux-cli/releases/download/v1.3.4/remnux-cli-linux.sha256.asc
    mode: '0755'

- name: Ensuring git and gnupg are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - git
    - gnupg

- name: Runing Remnux installer
  ansible.builtin.command: remnux install --mode=cloud

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:

- name: Updating Remnux VM
  ansible.builtin.command: remnux update

- name: Upgrading Remnux VM
  ansible.builtin.command: remnux upgrade

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:
