---
- name: Adding SaltStack apt repo key
  ansible.builtin.apt_key:
    url: "{{ saltstack_repo }}/salt-archive-keyring.gpg"
    state: present

- name: Adding SaltStack apt repo
  ansible.builtin.apt_repository:
    repo: deb {{ saltstack_repo }} focal main
    filename: salt
    state: present

- name: Installing dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - "{{ remnux_deps }}"

- name: Stopping and disabling salt-minion service
  ansible.builtin.systemd:
    name: salt-minion
    state: stopped
    enabled: false

- name: Fetching Remnux installer
  ansible.builtin.get_url:
    url: "{{ remnux_installer }}"
    dest: /usr/local/bin/remnux
    checksum: sha256:{{ remnux_checksum }}
    mode: '0755'

- name: Runing Remnux installer
  ansible.builtin.shell:
    cmd: remnux install --mode=cloud --user=vagrant

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:

- name: Ensuring password is set to 'vagrant'
  ansible.builtin.shell:
    cmd: echo 'vagrant:vagrant' | chpasswd

- name: Updating Remnux VM
  ansible.builtin.shell:
    cmd: remnux update

- name: Updating Remnux VM
  ansible.builtin.shell:
    cmd: remnux upgrade

- name: Disabling systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true

- name: Rebooting machine to make changes take effect
  ansible.builtin.reboot:
